"""Design generation - the one feature in this system with a real per-call cost.

Added beyond the original sprint scope, at explicit user request. Every other
model call here produces a small structured object; this one produces an image
and is priced per generation (a few cents on OpenRouter at the time this was
written). See the README's Design attachment section for the cost note users
actually see.

The generated bytes are pushed through :func:`app.security.uploads.store_upload`
- the exact same magic-byte validation a client upload receives. That is
deliberate defense in depth: if the image model ever returns something that is
not actually a valid image (a refusal rendered as text-in-an-image-field, a
malformed payload), it is rejected the same way a disguised file upload would
be, rather than trusted because it came from "our own" call.

No image understanding happens here or anywhere else in this codebase. The
generated file is stored and referenced by id; nothing reads its content back
into the agent. That boundary is unchanged from the original scope decision.
"""

from __future__ import annotations

import logging

from app.config import Settings, get_settings
from app.llm.factory import ImageProvider, LLMError
from app.logging_config import Event, log_event, redact_text
from app.security.uploads import UploadRecord, UploadRejectedError, store_upload

logger = logging.getLogger(__name__)


class DesignGenerationError(RuntimeError):
    """Generation or storage failed. The message is safe to show a user."""


def generate_design(
    prompt: str, provider: ImageProvider, settings: Settings | None = None
) -> UploadRecord:
    """Generate an image from ``prompt`` and store it like any other upload.

    Raises :class:`DesignGenerationError` on any failure - a model refusal, a
    provider outage, or bytes that fail the same validation a real upload would.
    """
    settings = settings or get_settings()
    log_event(logger, Event.DESIGN_GENERATION_STARTED, **redact_text(prompt))

    try:
        image_bytes = provider.generate_image(prompt)
    except LLMError as error:
        raise DesignGenerationError(str(error)) from error

    try:
        record = store_upload("generated-design.png", image_bytes, settings)
    except UploadRejectedError as rejection:
        # A model returning unusable bytes is a provider failure from the
        # caller's point of view, not a validation mistake the user made -
        # translate it rather than leaking the upload-specific wording.
        raise DesignGenerationError(
            "The generated image could not be saved. Please try again."
        ) from rejection

    log_event(
        logger,
        Event.DESIGN_GENERATION_COMPLETED,
        upload_id=record.upload_id,
        size_bytes=record.size_bytes,
    )
    return record
